# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - KEYCLOAK_URL=http://keycloak:8181
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - ORDER_SERVICE_URL=http://order-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
      - ZIPKIN_URL=http://tempo:9411
    ports:
      - 9000:9000
    networks:
      - lgtm-network
    depends_on:
      - keycloak
      - loki
      - tempo
  keycloak-mysql:
    image: mysql:8.4.9
    container_name: keycloak_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak_password
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_DATABASE: keycloak

      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_ENABLED: true
    ports:
      - 8181:8080
    volumes:
      - "./docker/keycloak/realms/:/opt/keycloak/data/import/"
    depends_on:
      - keycloak-mysql
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - lgtm-network
  prometheus:
    image: prom/prometheus:latest
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090" # Optional: useful if you want to see the raw Prometheus UI
    networks:
      - lgtm-network
  # Grafana Tempo Tracing Backend
  tempo:
    image: grafana/tempo:2.10.0
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200" # Tempo search / frontend engine port (for Grafana UI)
      - "9411:9411" # Zipkin compatibility port (where Spring app pushes traces)
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - tempo_data:/var/tempo
    networks:
      - lgtm-network
  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default UI login: admin / admin
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      # Mounts your datasource file into Grafana's automatic provisioning directory
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    networks:
      - lgtm-network

# Essential: Explicitly defining the shared communication bridge
networks:
  lgtm-network:
    driver: bridge

volumes:
  mysql_data:
  tempo_data:

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

