server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This line forces Nginx to fall back to index.html for SPA routing
        try_files $uri $uri/ /index.html;
    }

    # --- TAMBAHKAN BLOK INI ---
    # Memaksa Nginx mencari file env-config.js secara mutlak tanpa fallback ke index.html
    location = /env-config.js {
        root /usr/share/nginx/html;
        default_type application/javascript;
        try_files $uri =404;
    }

    # Optional: Enable gzip compression for better performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
