# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #application
  - manifests/applications/api-gateway.yaml
  - manifests/applications/common-config.yaml
  - manifests/applications/frontend.yaml
  - manifests/applications/inventory-service.yaml
  - manifests/applications/notification-service.yaml
  - manifests/applications/order-service.yaml
  - manifests/applications/product-service.yaml
  # infrastructure
  - manifests/infrastructure/grafana.yaml
  - manifests/infrastructure/kafka-ui.yaml
  - manifests/infrastructure/kafka.yaml
  - manifests/infrastructure/keycloak.yaml
  - manifests/infrastructure/loki.yaml
  - manifests/infrastructure/mongodb.yaml
  - manifests/infrastructure/mysql.yaml
  - manifests/infrastructure/prometheus.yaml
  - manifests/infrastructure/schema-registry.yaml
  - manifests/infrastructure/tempo.yaml
  - manifests/infrastructure/ingress.yaml

