apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.10.0
          args: ['-config.file=/etc/tempo.yaml']
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-data
              mountPath: /var/tempo
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 3200
              name: tempo
            - containerPort: 9411
              name: zipkin
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
      name: tempo
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: zipkin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    stream_over_http_enabled: true
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:
          endpoint: 0.0.0.0:9411

    ingester:
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 24h # Retain local traces for 24 hours

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/blocks
        wal:
          path: /var/tempo/wal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /tmp/tempo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
