apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: haraif/microservice-frontend:latest
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
          env:
            - name: VITE_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUBLIC_API_URL
                  name: frontend-configmap
            - name: VITE_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_KEYCLOAK_URL
                  name: frontend-configmap
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  key: VITE_KEYCLOAK_REALM
                  name: frontend-configmap
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: VITE_KEYCLOAK_CLIENT_ID
                  name: frontend-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  VITE_PUBLIC_API_URL: http://api-gateway.default.svc.cluster.local:9000
  VITE_KEYCLOAK_URL: http://keycloak.default.svc.cluster.local:8080
  VITE_KEYCLOAK_REALM: spring-microservice-security-realm
  VITE_KEYCLOAK_CLIENT_ID: react-marketplace-id
