apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-service-server
          image: haraif/notification-service-server:latest
          resources:
            requests:
              memory: '512Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '1000m'
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
                  name: common-config
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
                  name: notification-config
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: 'http://schema-registry.default.svc.cluster.local:8081'
